### ISSUE TITLE
Return meaningful exit status

### ISSUE THREAD

**Issue by Mq89** [islandoftex/checkcites#11]
For automatised testing etc. it would be helpful if the script returned something other than 0 if unused or undefined references were found.

**Comment by Mq89** [comment]
I think the current version does it already. Had an older one with my distribution.

**Comment by cereda** [comment]
Hi Markus, thank you very much for your issue and also for helping me remember my own code! It's been a while! :wink: 

Should you need any assistance or want to suggest any features and/or improvements, please write to us! You can open another issue at any time.

Have a nice weekend! Stay safe!
